# Logistic regression

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
from sklearn.linear_model import LogisticRegression

In [11]:
df = pd.read_csv("../datasets/Iris.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [12]:
df = df.iloc[:100 , :]
df = df.drop("Id", axis=1)
df["Species"] = df["Species"].apply(lambda x: 0 if x=="Iris-setosa" else 1)
df

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0             5.1           3.5            1.4           0.2        0
1             4.9           3.0            1.4           0.2        0
2             4.7           3.2            1.3           0.2        0
3             4.6           3.1            1.5           0.2        0
4             5.0           3.6            1.4           0.2        0
..            ...           ...            ...           ...      ...
95            5.7           3.0            4.2           1.2        1
96            5.7           2.9            4.2           1.3        1
97            6.2           2.9            4.3           1.3        1
98            5.1           2.5            3.0           1.1        1
99            5.7           2.8            4.1           1.3        1

[100 rows x 5 columns]

In [13]:
y_train = df["Species"]
x_train = df.drop("Species", axis=1)

y_train = np.array(y_train).reshape((-1, 1))
x_train = np.array(x_train)
x_train

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3]])

Сигмоида:

In [14]:
def g(z): 
    z = np.clip(z, -500, 500)
    response = 1 / (1 + np.exp(-z))
    return response

In [15]:
len(x_train)

100

### Градиент функции потерь

In [16]:
size_of_features = x_train.shape[1]
np.random.seed(21)
w = np.random.randn(size_of_features).reshape((size_of_features,-1)) #начальные веса
alpha = 0.1 

w

array([[-0.05196425],
       [-0.11119605],
       [ 1.0417968 ],
       [-1.25673929]])

In [17]:
z = 0
iterator = 0
loss = np.zeros(size_of_features).reshape((size_of_features,-1))
prev_loss = np.zeros(size_of_features).reshape((size_of_features,-1))
while True:
    loss = np.zeros(size_of_features).reshape((size_of_features,-1))
    for i in range(len(x_train)):  # цикл подсчета градиента от loss (идем по каждой строке датафрейма (100 операций))
        z=0
        x = x_train[i]
        for j in range(size_of_features):
            z += x[j] * w[j]                # z = w1*x1 + w2*x2 + w3*x3 ...
        err = (y_train[i] - g(z))
        for j in range(size_of_features):
            loss[j] -= x[j] * err           # Подсчет градиента от функции потерь

    iterator +=1
    #if (abs(prev_loss) - abs(loss)).all() < 1e-4:
    if np.linalg.norm(loss) < 1e-4:
    #if iterator == 100:
        break
    w = w - np.dot(alpha, loss)
    prev_loss = loss
loss, iterator

(array([[6.77862190e-07],
        [3.50487012e-07],
        [1.97839622e-07],
        [4.47740657e-08]]),
 6)

In [18]:
predict = np.zeros(len(y_train)).reshape((-1, 1))
list_of_predict = list()
z_predicted = x_train.dot(w)
for i in range(len(z_predicted)):
    predict[i] = g(z_predicted[i])
    if predict[i] < 0.5:
        predict[i] = 0
    else:
        predict[i] = 1
    list_of_predict.append(predict[i])

list_of_predict = [x.item() for x in list_of_predict]
df_predict = pd.Series(list_of_predict).astype('Int64')
df_predict.value_counts()

0    50
1    50
Name: count, dtype: Int64

In [19]:
comparison = pd.DataFrame({"Actual data": df["Species"], "NUMPY predict": df_predict})
comparison.head(40)

    Actual data  NUMPY predict
0             0              0
1             0              0
2             0              0
3             0              0
4             0              0
5             0              0
6             0              0
7             0              0
8             0              0
9             0              0
10            0              0
11            0              0
12            0              0
13            0              0
14            0              0
15            0              0
16            0              0
17            0              0
18            0              0
19            0              0
20            0              0
21            0              0
22            0              0
23            0              0
24            0              0
25            0              0
26            0              0
27            0              0
28            0              0
29            0              0
30            0              0
31            0              0
32            0              0
33            0              0
34            0              0
35            0              0
36            0              0
37            0              0
38            0              0
39            0              0

## Сверим работу модели с работой LogisticRegression из sklearn

In [20]:
clf = LogisticRegression()
clf.fit(x_train, y_train)

/home/user/ML-Toolkit/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [21]:
sklearn_predict = clf.predict(x_train)
comparison['sklearn predict'] = sklearn_predict

In [22]:
comparison.tail(45)

    Actual data  NUMPY predict  sklearn predict
55            1              1                1
56            1              1                1
57            1              1                1
58            1              1                1
59            1              1                1
60            1              1                1
61            1              1                1
62            1              1                1
63            1              1                1
64            1              1                1
65            1              1                1
66            1              1                1
67            1              1                1
68            1              1                1
69            1              1                1
70            1              1                1
71            1              1                1
72            1              1                1
73            1              1                1
74            1              1                1
75            1              1                1
76            1              1                1
77            1              1                1
78            1              1                1
79            1              1                1
80            1              1                1
81            1              1                1
82            1              1                1
83            1              1                1
84            1              1                1
85            1              1                1
86            1              1                1
87            1              1                1
88            1              1                1
89            1              1                1
90            1              1                1
91            1              1                1
92            1              1                1
93            1              1                1
94            1              1                1
95            1              1                1
96            1              1                1
97            1              1                1
98            1              1                1
99            1              1                1

In [23]:
numpy_error = comparison['Actual data'] - comparison['NUMPY predict']
counts_numpy_error = numpy_error[numpy_error != 0].count()

sklearn_error = comparison['Actual data'] - comparison['sklearn predict']
counts_sklearn_error = sklearn_error[sklearn_error != 0].count()

print("Количество ошибочных прогнозов модели, реализованной на NUMPY:")
print(f"{counts_numpy_error} из {len(y_train)}\n")
print("Количество ошибочных прогнозов модели, реализованной в scikit-learn:")
print(f"{counts_sklearn_error} из {len(y_train)}")

Количество ошибочных прогнозов модели, реализованной на NUMPY:
0 из 100

Количество ошибочных прогнозов модели, реализованной в scikit-learn:
0 из 100